var character = [
	'Nick Swardson',
	'Old Gays',
	'Witcher X 2',
	'Zoomies',
	'Rev MLK',
	'Janet',
	'Atwood Lesbians',
	'Jake',
	'Hands Dancer',
	'White Glasses',
	'Jakes Harem',
	'Chris Ex',
	'Fitness Goth',
	'Guy on Leash',
	'Guy in gym shorts',
	'Mohawk/suit Guy',
	'Strap Gays',
	'Rainbow Brite',
	'Stinky Tail Guy',
	'Furries',
	'Bill Maher Jr.',
	'Fire Breather',
	'Vic',
	'Topless Woman',
	'Bad GoGo Dancer',
	'Stinky Underarm Smell',
];
